---
services:
  db:
    container_name: code-review-db
    image: postgres:16-alpine

    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devdata
      POSTGRES_DB: code_review_dev

volumes:
  pgdata:
    driver: local
