[tool.ruff]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "T10", "CPY"]

[tool.ruff.lint.isort]
known-first-party = ["code_review_backend", "code_review_bot", "code_review_tools", "code_review_events"]
