[build-system]
requires = ["setuptools==74.1.2", "setuptools-scm==8.1.0"]

[tool.ruff]

[tool.ruff.lint]
select = ["W", "E", "F", "I", "T10", "UP"]
ignore = [
	# Line too long
	"E501",
]

[tool.ruff.lint.isort]
known-first-party = ["code_review_backend", "code_review_bot", "code_review_tools"]
